/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type ColorWork = {
  _id: string;
  _type: "colorWork";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: {
    es?: string;
    en?: string;
  };
  slug?: Slug;
  date?: string;
  client?: string;
  director?: string;
  production?: string;
  mainImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  vimeoEmbed?: string;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  additionalInfo?: {
    es?: BlockContent;
    en?: BlockContent;
  };
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal";
  listItem?: never;
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type DpWork = {
  _id: string;
  _type: "dpWork";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: {
    es?: string;
    en?: string;
  };
  slug?: Slug;
  date?: string;
  client?: string;
  director?: string;
  production?: string;
  mainImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  vimeoEmbed?: string;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  additionalInfo?: {
    es?: BlockContent;
    en?: BlockContent;
  };
};

export type GeneralData = {
  _id: string;
  _type: "generalData";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  detail?: {
    es?: string;
    en?: string;
  };
  coverVideo?: string;
  coverThumbnail?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  colorTitle?: {
    es?: string;
    en?: string;
  };
  bio?: {
    es?: BlockContent;
    en?: BlockContent;
  };
  profileImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  links?: Array<{
    title?: string;
    url?: string;
    _type: "link";
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = ColorWork | BlockContent | SanityImageCrop | SanityImageHotspot | Slug | DpWork | GeneralData | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ../nicocroes/src/lib/dataQueries.ts
// Variable: generalDataQuery
// Query: *[_type == "generalData"][0]{    name,    detail,    coverVideo,    coverThumbnail,    colorTitle,    bio,    profileImage,    links  }
export type GeneralDataQueryResult = {
  name: string | null;
  detail: {
    es?: string;
    en?: string;
  } | null;
  coverVideo: string | null;
  coverThumbnail: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  colorTitle: {
    es?: string;
    en?: string;
  } | null;
  bio: {
    es?: BlockContent;
    en?: BlockContent;
  } | null;
  profileImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  links: Array<{
    title?: string;
    url?: string;
    _type: "link";
    _key: string;
  }> | null;
} | null;
// Variable: dpWorksListQuery
// Query: *[_type == "dpWork"] | order(date desc){    _id,    title,    slug,    date,    client,    director,    production,    mainImage,  }
export type DpWorksListQueryResult = Array<{
  _id: string;
  title: {
    es?: string;
    en?: string;
  } | null;
  slug: Slug | null;
  date: string | null;
  client: string | null;
  director: string | null;
  production: string | null;
  mainImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
}>;
// Variable: dpWorkBySlugQuery
// Query: *[_type == "dpWork" && slug.current == $slug][0]{    _id,    title,    slug,    date,    client,    director,    production,    mainImage,    vimeoEmbed,    images,    additionalInfo,  }
export type DpWorkBySlugQueryResult = {
  _id: string;
  title: {
    es?: string;
    en?: string;
  } | null;
  slug: Slug | null;
  date: string | null;
  client: string | null;
  director: string | null;
  production: string | null;
  mainImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  vimeoEmbed: string | null;
  images: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }> | null;
  additionalInfo: {
    es?: BlockContent;
    en?: BlockContent;
  } | null;
} | null;
// Variable: colorWorksListQuery
// Query: *[_type == "colorWork"] | order(date desc){    _id,    title,    slug,    date,    client,    director,    production,    mainImage,  }
export type ColorWorksListQueryResult = Array<{
  _id: string;
  title: {
    es?: string;
    en?: string;
  } | null;
  slug: Slug | null;
  date: string | null;
  client: string | null;
  director: string | null;
  production: string | null;
  mainImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
}>;
// Variable: colorWorkBySlugQuery
// Query: *[_type == "colorWork" && slug.current == $slug][0]{    _id,    title,    slug,    date,    client,    director,    production,    mainImage,    vimeoEmbed,    images,    additionalInfo,  }
export type ColorWorkBySlugQueryResult = {
  _id: string;
  title: {
    es?: string;
    en?: string;
  } | null;
  slug: Slug | null;
  date: string | null;
  client: string | null;
  director: string | null;
  production: string | null;
  mainImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  vimeoEmbed: string | null;
  images: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }> | null;
  additionalInfo: {
    es?: BlockContent;
    en?: BlockContent;
  } | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_type == \"generalData\"][0]{\n    name,\n    detail,\n    coverVideo,\n    coverThumbnail,\n    colorTitle,\n    bio,\n    profileImage,\n    links\n  }": GeneralDataQueryResult;
    "\n  *[_type == \"dpWork\"] | order(date desc){\n    _id,\n    title,\n    slug,\n    date,\n    client,\n    director,\n    production,\n    mainImage,\n  }": DpWorksListQueryResult;
    "\n  *[_type == \"dpWork\" && slug.current == $slug][0]{\n    _id,\n    title,\n    slug,\n    date,\n    client,\n    director,\n    production,\n    mainImage,\n    vimeoEmbed,\n    images,\n    additionalInfo,\n  }": DpWorkBySlugQueryResult;
    "\n  *[_type == \"colorWork\"] | order(date desc){\n    _id,\n    title,\n    slug,\n    date,\n    client,\n    director,\n    production,\n    mainImage,\n  }": ColorWorksListQueryResult;
    "\n  *[_type == \"colorWork\" && slug.current == $slug][0]{\n    _id,\n    title,\n    slug,\n    date,\n    client,\n    director,\n    production,\n    mainImage,\n    vimeoEmbed,\n    images,\n    additionalInfo,\n  }": ColorWorkBySlugQueryResult;
  }
}
